# basic options
title: Robert's Portfolio
author: Robert Abugel
email: abugelrobert@gmail.com
description: This is just a place to show my work
github_username:  bobabugel

# Build settings
markdown: kramdown
theme: minima
